### ISSUE TITLE
Exclude rule doesn't work

### ISSUE THREAD

**Issue by fratt-elca** [SverrirValgeirsson/Todour#22] opened 2021-02-16 15:49 UTC
I have tasks tagged with `@other`.

If I search for `-@other`, it doesn't return anything. It should return all tasks that don't contain `@other`.

**Comment by SverrirValgeirsson** [comment] 2021-02-16 19:18
Hi. No, if you do !@other you will hopefully get the results you expect. (-@other will search for a literal match of "-@other").

**Comment by Moonbase59** [comment] 2021-02-26 00:34
I can confirm this works fine on Linux Mint 20.1 (using »!« as »NOT«).

**Comment by SverrirValgeirsson** [comment] 2021-02-28 11:59
I will close this as it seems to be working as it should.

**Closed by SverrirValgeirsson** 2021-02-28 11:59 UTC

**Comment by fratt-elca** [comment] 2021-03-02 09:24
Fine for me, even though that's not how the CLI behaves : https://github.com/todotxt/todo.txt-cli/blob/master/USAGE.md#list

Thanks!

**Comment by SverrirValgeirsson** [comment] 2021-03-02 09:48
Never used the CLI so I didn't even think of the option :) I might add support for it later. Not a hard thing to do (and I doubt it breaks anything)

**Comment by SverrirValgeirsson** [comment] 2021-03-13 20:37
Hi again. Added the option to select whatever symbol you want. Will be in 2.20 :) 

![bild](https://user-images.githubusercontent.com/3577564/111043717-509c5f80-8444-11eb-97e1-9feaef27687d.png)
